FROM gradle:3.5-alpine
MAINTAINER Jack Du <dujiaxi@chachazhan.com>

COPY . /etc/source
WORKDIR /etc/source

USER root
RUN chown -R gradle /etc/source

USER gradle
RUN gradle -Dfile.encoding=UTF-8 --stacktrace build && \
    mv build/libs/*.jar /home/gradle/server.jar